sudo apt-get install build-essential cmake;
sudo apt-get install bzr build-essential;
sudo apt-get install python-dev;
sudo apt-get install ruby-dev;
sudo apt-get install openjdk-6-jdk;
sudo apt-get install libxml2-dev;
sudo apt-get install uuid-dev;
sudo apt-get install libicu-dev;
sudo apt-get install libxerces-c-dev;
sudo apt-get install libxslt-dev;
sudo apt-get install libcurl4-openssl-dev;
sudo apt-get install swig;
sudo apt-get install libaccess-bridge-java-jni;
sudo apt-get install libtidy-dev;
